### PR TITLE
prepare arxiv version

### PR DESCRIPTION
**Pull request by faroit**
More files removed

### CODE REVIEW

**Comment by faroit** [comment]
@umutsimsekli how do you usually merge  appendix and main tex file?

**Comment by umutsimsekli** [comment]
> @umutsimsekli how do you usually merge appendix and main tex file?

I don't really remember tbh, here's what I did for icml2017 

https://www.dropbox.com/s/5fva5v9lrgzvcti/ICML2017.zip?dl=0

I'm on holidays at the moment, if you don't want to do it I can do it next week.

**Comment by faroit** [comment]
> I don't really remember tbh, here's what I did for icml2017

great that helps, thanks

**Comment by faroit** [comment]
okay, done.

1. please, check the output: [icml_2019_sketchmcmc.pdf](https://github.com/aliutkus/swf/files/3265875/icml_2019_sketchmcmc.pdf)
2. do you want a separate supplementary references section?

**Comment by faroit** [comment]
ping @umutsimsekli @aliutkus

**Comment by aliutkus** [comment]
looks good to me

**Comment by umutsimsekli** [comment]
As a grandfather I don't know how to pull this to my computer. Should I click on "merge pull request"?

**Comment by faroit** [comment]
@umutsimsekli 

* if you want to make changes you need to checkout the pull request 
* if you think the pdf looks ok, you can click merge, yes
* if you just want to see the code of this pull request, you can download it [here](https://github.com/faroit/swf/archive/arxiv.zip)

**Comment by faroit** [comment]
well, too late ;-) tell me if there is anything to do.

**Comment by umutsimsekli** [comment]
are all the figures used? there are a million of them

**Comment by faroit** [comment]
I think the script I used went through the code and checked if a figure was used or not and then removed those.

@aliutkus did you check the folders?

**Pull request merged**
