### PR TITLE
Update environment

### PR DESCRIPTION
**Pull request by cifkao**

### CODE REVIEW

**Comment by aliutkus** [comment]
thanks for this, does it work with the latest versions for qsketch etc ?

**Comment by cifkao** [comment]
Actually, I can't get the latest version of torchsearchsorted to install, I ran into that just now. I'm going to add the version spec for it.

As for qsketch, the version in environment_gpu.yml is 0.1, but the only release on GitHub is 1.0, which gives me this error:
```
  Cloning https://github.com/aliutkus/qsketch.git (to v1.0) to /tmp/pip-d295xd9s-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tsi/doctorants/ocifka/envs/SWF/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-d295xd9s-build/setup.py'
```
The latest version from master installs successfully, but I haven't tried running anything yet. Should I use that, or do you have a specific commit I should use instead?

**Comment by aliutkus** [comment]
are you using pytorch 1.4 ? the latest version uses stuff from there

**Comment by aliutkus** [comment]
do you have some instant messaging system ? 
I'm on whatsap +33662227080 
and I can also use slack or mattermost 

I understand it's a bit difficult to get into the SWF thing. 
I hope the code is understandable 

actually, the algorithm is pretty simple, you could directly use the torchinterp1d and torchpercentile function and reprogram it yourself taking inspiration from this: 
the core thing you need to understand are lines 80-118 of swf.py 

please let me know if you need help

**Comment by cifkao** [comment]
Okay, here's an environment that seems to work!

**Pull request merged**
